%Project Euler Problem 29
%Find how many distinct numbers are in a sequence generated by a^b for
%2<=a<=100 and 2<=b<=100

clear

power=[];
for a=2:100
    for b=2:100
        if ismember(a^b,power)==0
            power=[power a^b];
        end
    end
end

n=length(power);
fprintf('a^b with 2<=a<=100 and 2<=b<=100 generates ')
fprintf('%d distinct numbers.\n',n)